In [2]:
# Creating an array
import numpy as np
a=np.array([1,2,3])
print(a.ndim)

1


In [4]:
# 2d array
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(b.ndim)

[[1 2 3]
 [4 5 6]]
2


In [8]:
# Basic properties
# print(b.itemsize)
# print(b.dtype)
# print(a.size)
# b.shape


(2, 3)

In [13]:
# Basic functions
# c=np.ones((2,3))
# c
d=np.arange(12).reshape(3,4)
print(d)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [17]:
# indexing and slicing
print(b)
print(b[1,1])



[[1 2 3]
 [4 5 6]]
5


In [20]:
# iterate through arrays
b
for i in b.flat:
    print(i)

1
2
3
4
5
6


In [24]:
# stacking arrays
x=np.array([[1,2,3],[4,5,6]])
print(x)
y=np.array([[1,2,3],[4,5,6]])
print(y)
print(np.hstack((x,y)))

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [30]:
# nditer
s=np.arange(20).reshape(4,5)
print(s)
for i in np.nditer(s,order='c'):
    print(i)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
